name: CI/CD Pipeline

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to AWS ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      env:
        AWS_DEFAULT_REGION: us-east-1  # Set your AWS region here
    # Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t $ECR_REPOSITORY:latest .
        docker tag $ECR_REPOSITORY:latest $ECR_REPOSITORY:latest
        docker push $ECR_REPOSITORY:latest
      env:
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    # Configure kubectl
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 -d > ~/.kube/config
        kubectl get nodes
      env:
        KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}

    # Deploy to Kubernetes
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/secret.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
